"""
@author: Julien Marchal (ILL Neutron detector Group) 
Do not modify the script without contacting the author (marchalj@ill.fr)
"""
# %%
import plotly.express as px
import asyncio
from nicegui import app,run,ui,html
import numpy as np
import matplotlib.pyplot as plt
import time
from datetime import date
# #import lib.det as det
# #import lib.detList as detList
import pandas as pd
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import json
#import webview
import csv
import matplotlib.animation as animation
from collections import deque
import ctypes
import math
import os

pi=3.14
GUI_test_mode=False
verbose=False

GUI_debug_mode=False
chatty=False
if not GUI_debug_mode:
    from scisdk.scisdk import SciSDK
    from scisdk.scisdk_defines import *


TRACES_COUNTER=0
ADC_SAMPLING_FREQ = 120E6 #MHz
IP=["10.128.00.50","10.128.00.100","10.128.00.150","10.128.00.200"]
register_filename_default='RegisterSettings.txt'
#register_filename_default='registers_file_test_pulse.txt'
GUIrefreshRate = 1  # GUI plot refreshing rate in Hz

def detList():
    # Create a Panda table with the specfications of the detectors which can be read-out by the CAEN R5560 using the charge-division method
    index=[ 'nbOfTubes','TubeLength','Tube width']# length and width in cm
    d = {'CSPEC': pd.Series([32,350,2.5],index),
         'MARMOT': pd.Series([30,60,4],index),
         '32 Tubes': pd.Series([32,100,1],index),
         '64 Tubes': pd.Series([64,100,1],index),
         '96 Tubes': pd.Series([96,100,1],index),
         '128 Tubes': pd.Series([128,100,1],index)
         }
    return(pd.DataFrame(d))

detParams=detList().to_dict('split')['columns'] # Get the types of available detectors from the table generated by the detList function 
detTypeList=dict(zip([i+1 for i in range(len(detParams))], detParams)) # Create a dictionary of available detector types to show in the GUI
acqModeList={1:'LIST', 2: 'POS', 3: 'PHS'} # Create a dictionary of acquisition modes to show in the GUI
nbOfFigsList=[2,1,1]# Number of figures produced for each acquisition mode. In List mode 2D plots of both positions and PHS are shown 
det_list=detList()
# GUI initialisation parameters
detTypeInit=1 # Initialise the GUI with detector type
acqModeInit=1 # Initialise the GUI in 2D acquisition mode
fig=[px.imshow(np.zeros([32,1024]),aspect=32*2.5/350,labels=dict(x="X channel", y="Y channel", color="Counts")) for f in np.arange(nbOfFigsList[acqModeInit-1])] # Initialise the GUI plot with a 128x128 blank image
pathInit = 'C:/Detector_data/'
serialNumberInit=1
subpathInit=detTypeList[detTypeInit]  +'/' + str(date.today())+'/'+acqModeList[acqModeInit]+'/'
filenameInit = 'data'
filenameInit = 'data'
traces_pathInit = pathInit
traces_subpathInit=detTypeList[detTypeInit]  + '_SN' +str(serialNumberInit).zfill(2) + '/' + str(date.today())+'/ANALOG_TRACES/'
traces_filenameInit = 'run_'
acqRunningFlag=0

def show_notification(message: str, id: str = "default"):
    notification=ui.notify(message, persistent=False,timeout=0.1).props("group='notifications'").style("z-index: 1000;")
    
def connect():
    #####################################################################################
    #  Open Communication with the ADC
    #####################################################################################
    sdk = SciSDK()  # initialize scisdk library
    t0=time.perf_counter() # start time
    ip="10.128.00.50"


    res = sdk.AddNewDevice("10.128.0.50:8888", "R5560", "RegisterFile.json", "board0")
    if res != 0:
        print(" ! Failed to connect, code:", res)
        exit(1)
    
    library_version = sdk.GetLibraryVersion()
    
    print("R5560 library version: " + str(library_version))

    return sdk

def disconnect(sdk):
    sdk.DetachDevice("board0")
    sdk.FreeLib()
    print("Device detached, SDK freed")

def check_data_folder():
    
        fullPath=traces_pathInput.value+'/'+traces_subpathInput.value 
        if os.path.exists(fullPath) == 0:
            os.makedirs(fullPath)
            print('Directory ' + fullPath + ' created')




def apply_scope_settings():
        
    # set oscilloscope parameters
    if verbose:
        print("\n --- Setting oscilloscope parameters:")


    if traces_autosaveCheckbox.value:
        check_data_folder()

    decimator = 1
    oscilloscopeChannel="Oscilloscope_"+str(int(tube_number.value))
    

    res = sdk.SetParameterString("board0:/MMCComponents/"+oscilloscopeChannel+".data_processing","decode")
    res = sdk.SetParameterInteger("board0:/MMCComponents/"+oscilloscopeChannel+".trigger_level", scope_threshold_slider.value)
    res = sdk.SetParameterString("board0:/MMCComponents/"+oscilloscopeChannel+".trigger_mode",scope_trigger_mode.value)
    res = sdk.SetParameterInteger("board0:/MMCComponents/"+oscilloscopeChannel+".trigger_channel", scope_trig_ch_button.options.index(scope_trig_ch_button.value))
    res = sdk.SetParameterInteger("board0:/MMCComponents/"+oscilloscopeChannel+".pretrigger", 150)
    res = sdk.SetParameterInteger("board0:/MMCComponents/"+oscilloscopeChannel+".decimator", decimator)
    res = sdk.SetParameterString("board0:/MMCComponents/"+oscilloscopeChannel+".acq_mode", "blocking")
    res = sdk.SetParameterInteger("board0:/MMCComponents/"+oscilloscopeChannel+".timeout", 500)
    # allocate buffer for oscilloscope

    res, buf_osc = sdk.AllocateBuffer("board0:/MMCComponents/"+oscilloscopeChannel)
    
    if verbose:
        if res != 0:
            print(" ! Failed to allocate buffer for oscilloscope, code:", res)
        else:
            print(" - Buffer allocated successfully for oscilloscope")

    return(buf_osc)




def update_all():
    # if chatty:
    #     print("### Acquire scope traces")

    registers_table_update()
    setADCsettings()
    buf_osc=apply_scope_settings()

    if not GUI_debug_mode:

        import concurrent.futures
        import time

        res_osc, buf_osc_local = sdk.ReadData("board0:/MMCComponents/Oscilloscope_"+str(int(tube_number.value)), buf_osc)
        print('########## '+str(res_osc))
        if res_osc == 0:
            # -------- ANALOG --------
            samples = buf_osc_local.info.samples_analog
            channels = buf_osc_local.info.channels

            # xar = [i * decimator for i in range(samples)]
            analog_time_axis=np.arange(samples)/(ADC_SAMPLING_FREQ*1E6)
            analog_traces = np.zeros([channels,samples])
            for ch in range(channels):
                start = ch * samples
                end = start + samples
                data = [buf_osc_local.analog[i] & 0xFFFF for i in range(start, end)]
                #lines_analog[ch].set_data(xar, data)
                analog_traces[ch]=data

            # -------- DIGITAL --------
            samples = buf_osc_local.info.samples_digital
            tracks = buf_osc_local.info.tracks_digital_per_channel
            
            DIGITAL_CHANNEL=2
            digital_time_axis=np.arange(samples)/(ADC_SAMPLING_FREQ*1E6)
            digital_traces = np.zeros([tracks,samples])
            for d in range(tracks):
                digital_wave = []

                for i in range(samples):
                    index = DIGITAL_CHANNEL * tracks * samples + d * samples + i
                    raw = buf_osc_local.digital[index] & 0xFF
                    bit = raw & 1
                    digital_wave.append(0.5 * bit + (tracks - d - 1))

                digital_traces[d, :] = digital_wave


            analog_line_plot.push(analog_time_axis, [analog_traces[0], analog_traces[1],analog_traces[2], analog_traces[3]])
            digital_line_plot.push(digital_time_axis, [digital_traces[0], digital_traces[1],digital_traces[2], digital_traces[3]])
    
            rms_val_ch1.value=np.std(analog_traces[0])
            rms_val_ch2.value=np.std(analog_traces[1])
            rms_val_ch3.value=np.std(analog_traces[2])
            rms_val_ch4.value=np.std(analog_traces[3])

            mean_val_ch1.value=np.mean(analog_traces[0])
            mean_val_ch2.value=np.mean(analog_traces[1])
            mean_val_ch3.value=np.mean(analog_traces[2])
            mean_val_ch4.value=np.mean(analog_traces[3])


            if traces_autosaveCheckbox.value:
                global TRACES_COUNTER
                fullPath=traces_pathInput.value+'/'+traces_subpathInput.value 
                # if os.path.exists(fullPath) == 0:
                #     os.makedirs(fullPath)
                #     print('Directory ' + fullPath + ' created')
                
                
                if TRACES_COUNTER<number_of_traces_input.value:
                    combined_array = np.column_stack((analog_traces[0], analog_traces[1],analog_traces[2], analog_traces[3]))
                    if os.path.isfile(fullPath+'idx.txt'):
                        fileIndex = np.loadtxt(fullPath+'idx.txt', dtype='int16')
                        fileIndex = fileIndex+1
                        dataFile=fullPath+traces_filenameInput.value+str("%05d" % fileIndex)+'.txt'
                        
                        np.savetxt(dataFile, combined_array , fmt='%i')
                        if chatty:
                            print('### Traces saved in : ' + dataFile)
                        np.savetxt(fullPath+'idx.txt',np.array([fileIndex], np.int32), fmt="%05d")    
                    else:
                        fileIndex = 1
                        np.savetxt(fullPath+'idx.txt',np.array([fileIndex], np.int32), fmt="%05d")
                        dataFile=fullPath+traces_filenameInput.value+str("%05d" % fileIndex)+'.txt'
                        
                        np.savetxt(dataFile, combined_array  , fmt='%i')
                        if chatty:
                            print('### Traces saved in : ' + dataFile)
                    #show_notification("Traces",id="message_1")
                    #show_notification('Saving traces', id="message_1") 
                    ui.notify("Saving traces")
                    TRACES_COUNTER=TRACES_COUNTER+1
                    print(TRACES_COUNTER)
                else:
                    traces_autosaveCheckbox.value=False
                    scope_switch.value=False
                    TRACES_COUNTER=0
                    print(TRACES_COUNTER)
                

        else:
            #show_notification('No trigger (check scope threshold)', id="message_1")
            # analog_traces = np.zeros([4,1024])
            # analog_line_plot.push(analog_time_axis, [analog_traces[0], analog_traces[1],analog_traces[2], analog_traces[3]])
            # digital_traces = np.zeros([4,1024])
            # digital_line_plot.push(digital_time_axis, [digital_traces[0], digital_traces[1],digital_traces[2], digital_traces[3]])
            # ui.update()
            print("############## no trigger")
            ui.notify('No trigger (check scope threshold)')
        ui.update()
    return
    
    # else:
    #     channels=4
    #     samples=1024
    #     analog_traces = np.zeros([channels,samples])
    #     digital_traces = np.zeros([channels,samples])
    #     for i in range(4):
    #         analog_traces[i]=np.random.poisson(lam=0.1+i,size=samples)+i
    #         digital_traces[i]=np.random.randint(2,size=samples)+i


    #     analog_time_axis=np.arange(1024)/(ADC_SAMPLING_FREQ*1E6)
    #     analog_line_plot.push(analog_time_axis, [analog_traces[0], analog_traces[1],analog_traces[2], analog_traces[3]])
    #     digital_line_plot.push(analog_time_axis, [digital_traces[0], digital_traces[1],digital_traces[2], digital_traces[3]])


    
    # rms_val_ch1.value=np.std(analog_traces[0])
    # rms_val_ch2.value=np.std(analog_traces[1])
    # rms_val_ch3.value=np.std(analog_traces[2])
    # rms_val_ch4.value=np.std(analog_traces[3])

    # mean_val_ch1.value=np.mean(analog_traces[0])
    # mean_val_ch2.value=np.mean(analog_traces[1])
    # mean_val_ch3.value=np.mean(analog_traces[2])
    # mean_val_ch4.value=np.mean(analog_traces[3])
    

    # if traces_autosaveCheckbox.value:
    #     global TRACES_COUNTER
    #     fullPath=traces_pathInput.value+'/'+traces_subpathInput.value 
    #     # if os.path.exists(fullPath) == 0:
    #     #     os.makedirs(fullPath)
    #     #     print('Directory ' + fullPath + ' created')
        
        
    #     if TRACES_COUNTER<number_of_traces_input.value:
    #         combined_array = np.column_stack((analog_traces[0], analog_traces[1],analog_traces[2], analog_traces[3]))
    #         if os.path.isfile(fullPath+'idx.txt'):
    #             fileIndex = np.loadtxt(fullPath+'idx.txt', dtype='int16')
    #             fileIndex = fileIndex+1
    #             dataFile=fullPath+traces_filenameInput.value+str("%05d" % fileIndex)+'.txt'
                
    #             np.savetxt(dataFile, combined_array , fmt='%i')
    #             if chatty:
    #                 print('### Traces saved in : ' + dataFile)
    #             np.savetxt(fullPath+'idx.txt',np.array([fileIndex], np.int32), fmt="%05d")    
    #         else:
    #             fileIndex = 1
    #             np.savetxt(fullPath+'idx.txt',np.array([fileIndex], np.int32), fmt="%05d")
    #             dataFile=fullPath+traces_filenameInput.value+str("%05d" % fileIndex)+'.txt'
                
    #             np.savetxt(dataFile, combined_array  , fmt='%i')
    #             if chatty:
    #                 print('### Traces saved in : ' + dataFile)
    #         #show_notification("Traces #"+str(TRACES_COUNTER),id="message_1")
    #         TRACES_COUNTER=TRACES_COUNTER+1
    #         print(TRACES_COUNTER)
    #     else:
    #         traces_autosaveCheckbox.value=False
    #         scope_switch.value=False
    #         TRACES_COUNTER=0
    #         print(TRACES_COUNTER)
    #     ui.update()
            



# def update_all():
#     registers_table_update()
#     setADCsettings()
#     buf_osc=apply_scope_settings()


#     import concurrent.futures
#     import time

#     res_osc, buf_osc_local = sdk.ReadData("board0:/MMCComponents/Oscilloscope_"+str(int(tube_number.value)), buf_osc)
    
#     if res_osc == 0:
#         # -------- ANALOG --------
#         samples = buf_osc_local.info.samples_analog
#         channels = buf_osc_local.info.channels

#         # xar = [i * decimator for i in range(samples)]
#         analog_time_axis=np.arange(samples)/(ADC_SAMPLING_FREQ*1E6)
#         analog_traces = np.zeros([channels,samples])
#         for ch in range(channels):
#             start = ch * samples
#             end = start + samples
#             data = [buf_osc_local.analog[i] & 0xFFFF for i in range(start, end)]
#             #lines_analog[ch].set_data(xar, data)
#             analog_traces[ch]=data

#         # -------- DIGITAL --------
#         samples = buf_osc_local.info.samples_digital
#         tracks = buf_osc_local.info.tracks_digital_per_channel
        
#         DIGITAL_CHANNEL=2
#         digital_time_axis=np.arange(samples)/(ADC_SAMPLING_FREQ*1E6)
#         digital_traces = np.zeros([tracks,samples])
#         for d in range(tracks):
#             digital_wave = []

#             for i in range(samples):
#                 index = DIGITAL_CHANNEL * tracks * samples + d * samples + i
#                 raw = buf_osc_local.digital[index] & 0xFF
#                 bit = raw & 1
#                 digital_wave.append(0.5 * bit + (tracks - d - 1))

#             digital_traces[d, :] = digital_wave


#         analog_line_plot.push(analog_time_axis, [analog_traces[0], analog_traces[1],analog_traces[2], analog_traces[3]])
#         digital_line_plot.push(digital_time_axis, [digital_traces[0], digital_traces[1],digital_traces[2], digital_traces[3]])
    

#     else:
#         show_notification('No trigger (check scope threshold)', id="message_1") 

#     return


def setADCsettings():

    #sdk=connect()

    print('Set ADC settings')
    for params in table.rows: 
        match params["type"]:
            case "Decimal":
                value_int=int(params["value"])
            case "Hexadecimal":
                value_int=int(params["value"],16)
        # Extract register short name (there are 3 prefix cases : EMPTY, PCFG_ and FINE_OFS_)
        # It seems that only the registers with name satarting with PCFG are defined in RegisterFile.json file
        if params["name"].startswith("PCFG_"):
            param_name = params["name"].replace("PCFG_", "")
            path = f"board0:/MMCComponents/PCFG.{param_name}"
            if verbose:
                print(f"Setting {param_name} at path {path} to value {value_int}")
            err = sdk.SetParameterInteger(path, value_int)

            # Read back to verify
            # err, read_val = sdk.GetParameterInteger(path)
            # if verbose:
            #     if err == 0:
            #         print(f"{params["name"]:15s} set to {read_val}")
            #     else:
            #         print(f"ERROR reading back {params["name"]}, code {err}")




        # elif params["name"].startswith("FINE_OFS_"):
        #     param_name = params["name"].replace("FINE_OFS_", "")
        #     path = f"board0:/MMCComponents/FINE_OFS.{param_name}"
        #     path= f"board0:/Analog/FINE_OFS.{param_name}"
        #     print(f"Setting {param_name} at path {path} to value {value_int}")
        #     err = sdk.SetParameterInteger(path, value_int)

            # # Read back to verify
            # err, read_val = sdk.GetParameterInteger(path)
            # if err == 0:
            #     print(f"{params["name"]:15s} set to {read_val}")
            # else:
            #     print(f"ERROR reading back {params["name"]}, code {err}")
        
        # else:
        #     param_name = params["name"]
        #     path = f"board0:/Registers/{param_name}"
        #     #print(f"Setting {param_name} at path {path} to value {value_int}")
        #     err = sdk.SetRegister(path, value_int)
        #     print(path)

        #     # Read back to verify
        #     err, read_val = sdk.GetRegister(path)
        #     if err == 0:
        #         print(f"{params["name"]:15s} set to {read_val}")
        #     else:
        #         print(f"ERROR reading back {params["name"]}, code {err}")
        # else:
        #     if params["name"] in MMCC_params:
        #         match params["type"]:
        #             case "Decimal":
        #                 print("SetParameterInteger :" + "board0:/MMCComponents/LOKI_REG.SELECT_INPUT" + " at integer value of "  + str(params["value"]))
        #             case "Hexadecimal":
        #                 print("SetParameterHexadecimal :" + "board0:/MMCComponents/LOKI_REG.SELECT_INPUT" + " at hexadecimal value of "  + str(params["value"]))
        #     else:
        #         print("Parameter not set")


    #disconnect(sdk)
    # #####################################################################################
    # #  Close Communication with the ADC
    # #####################################################################################
    # sdk = SciSDK()  # initialize scisdk library
    # t0=time.perf_counter() # start time
    # ip="10.128.00.50"
    # res = sdk.DetachDevice("board0") #DT5560

    return

def getADCsettings():

    #sdk=connect()    
    print('Get registers')
    #res, buf = sdk.AllocateBuffer("board0:/MMCComponents/Oscilloscope_0")
    #res, buf = sdk.ReadData("board0:/MMCComponents/Oscilloscope_0", buf)
    value=0
    sdk.GetRegister("board:/Registers/TOSW",value)
    print(value)
    #for params in table.rows: 
        #print(buf)
#   if params["name"] in register_params:
#             match params["type"]:
#                 case "Decimal":
#                     print("GetParameterInteger :" + "board0:/Registers/LOKI_REG.SELECT_INPUT" )
# 
#                 case "Hexadecimal":
#                     print("GetParameterHexadecimal :" + "board0:/Registers/LOKI_REG.SELECT_INPUT")
#         else:
#             if params["name"] in MMCC_params:
#                 match params["type"]:
#                     case "Decimal":
#                         print("GetParameterInteger :" + "board0:/MMCComponents/LOKI_REG.SELECT_INPUT" )
#                     case "Hexadecimal":
#                         print("GetParameterHexadecimal :" + "board0:/MMCComponents/LOKI_REG.SELECT_INPUT")
#             else:
#                 print("Parameter not set")
    #disconnect(sdk)
    return

def openRegisterFile(register_filename):
    reg_dict={};reg_rows=[];reg_items = ['name', 'type', 'address', 'value']
    reg_columns= [
        {'name': 'name', 'label': 'Name', 'field': 'name', 'align': 'left'},
        {'name': 'type', 'label': 'Type', 'field': 'type', 'align': 'right'},
        {'name': 'address', 'label': 'Address', 'field': 'address', 'align': 'right'},
        {'name': 'value', 'label': 'Value', 'field': 'value', 'align': 'right'},
    ]
    try:
        with open(register_filename, 'r') as file:
            next(file)
            reader = csv.reader(file, delimiter=';')
            for row in reader:
                print(row)
                if len(row) == 5:
                    row.pop(3)  # L'index 3 correspond au quatrième élément 
                reg_dict={reg_items[index]:value for index,value in enumerate(row)}
                #print(reg_dict)
                reg_rows.append(reg_dict)
            
    except FileNotFoundError:
        print("Error: File not found")
    

    return reg_rows,reg_columns

def saveRegisterFile(register_filename,reg_rows):
    reg_items = ['name', 'type', 'address', 'value']
    with open(register_filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile,delimiter=';')
        writer.writerows([reg_items])
        [writer.writerows([reg_rows[n].values()]) for n in range(np.size(reg_rows))]
        [print([reg_rows[n].values()]) for n in range(np.size(reg_rows))]
    return

def readData():
    #print("Acquisition running")
    return

async def startAcq():
    print("Acquisition started")
    notif = ui.notification(timeout=None,spinner=True,position="bottom-left")
    if startToggleButton._state:
        for nIm in range(np.int16(expN.value)):
            if startToggleButton._state :
                frameNb = 1 
                t0 = time.time()
                while time.time() < t0 + expT.value and startToggleButton._state==1:
                    while time.time() < t0+frameNb*(1/GUIrefreshRate) and startToggleButton._state==1:
                        await run.io_bound(readData)
                    if startToggleButton._state==1:
                        t=time.time()
                        notif.message = 'Acquisition : '+ str(nIm+1)+ '/'+str(np.int16(expN.value)) + ' ; Exposure time : ' + str(np.int16(t-t0))+'s/'+str(np.int16(expT.value))+'s'
                        frameNb = frameNb+1

            #await asyncio.sleep(0.2)
            #await asyncio.sleep(0.2)
            #if d.acqMode != 'dump1D' and d.acqMode != 'dump2D':
        p.set_visibility(1)
    else:
        pass
    notif.dismiss()
    ui.update

def detTypeButton_change():
    subpathInput.value=detTypeList.get(detType.value)  +'/' + str(date.today())+'/'+acqModeList.get(acqMode.value)+'/'
    ui.update
    acqModeButton_change()  
    return

def acqModeButton_change():
    subpathInput.value=detTypeList.get(detType.value)  +'/' + str(date.today())+'/'+acqModeList.get(acqMode.value)+'/'
    match acqModeList.get(acqMode.value):
        case '1D':
            FIGURE.figure=fig1D[0]
        case '2D':
            FIGURE.figure=fig2D[0]
        case 'dump1D':
            FIGURE.figure=figdump1D[0]
        case 'dump2D':
            FIGURE.figure=figdump1D[0]
    FIGURE.style['display']='none'
    FIGURE.update()
    p.max=nbOfFigsList[acqMode.value-1]
    p.set_visibility(0)
    ui.update
    return

class ToggleButton(ui.button):
    def __init__(self, *args, **kwargs) -> None:
        
        self._state = False
        super().__init__(*args, **kwargs)
        self.on('click', self.toggle)

    async def toggle(self) -> None:
        """Toggle the button state."""
        if not self._state:
            self._state = not self._state
            self.update()
            await asyncio.sleep(1)
            await startAcq()
            if self._state:
                self._state = not self._state
                self.set_visibility(1)
            self.update()
            self.enable
        else :
            #self.set_visibility(0)
            self._state = not self._state
            self.update()
            self.disable
            await asyncio.sleep(1)
            #self.set_visibility(1)
            self.enable
            #self.update()  
        #time.sleep(2)

    def update(self) -> None:
        print("inside update function")
        self.props(f'color={"red" if self._state else "blue"}')
        self.props(f'icon={"block" if self._state else "ads_click"}')
        if self._state : 
            self.text="Stop"
        else :
            self.text="Start"
        super().update()

def autosave_click(): 
    match autosaveCheckbox.value:
        case 0:
            pathInput.visible=False
            subpathInput.visible=False
            filenameInput.visible=False
        case 1: 
            pathInput.visible=True
            subpathInput.visible=True
            filenameInput.visible=True
    ui.update
    return

def traces_autosave_click(): 
    match traces_autosaveCheckbox.value:
        case 0:
            number_of_traces_input.visible=False
            traces_pathInput.visible=False
            traces_subpathInput.visible=False
            traces_filenameInput.visible=False
        case 1: 
            number_of_traces_input.visible=True
            traces_pathInput.visible=True
            traces_subpathInput.visible=True
            traces_filenameInput.visible=True
    ui.update
    return

def serialNumberButton_change():
    print("")


async def update_fig():
    print(len(fig))
    if len(fig)==1:
        FIGURE.figure=fig[0]
    else:
        FIGURE.figure=fig[p.value-1]
    FIGURE.update()

def get_value(rows, key_search, value_search, key_return):
    """
    Retourne la valeur associée à `key_return` dans la première ligne où
    `key_search` == `value_search`. Retourne None si aucune ligne ne correspond.
    """
    for row in rows:
        if row.get(key_search) == value_search:
            return row.get(key_return)
    return None

def scope_parameters_update():    
    # update a parameter value in the oscilloscope menu based on the registers values present in the register menu
    Trigger_Thresh.value=get_value(table.rows,'name', 'PCFG_THRS','value')
    Trigger_Source.value=(Trigger_Source.options[int(get_value(table.rows,'name', 'PCFG_TRG_SOURCE','value'))])
    Trigger_Mode.value=(Trigger_Mode.options[int(get_value(table.rows,'name', 'PCFG_TRG_MODE','value'))])
    Trigger_hysteresis.value=get_value(table.rows,'name', 'PCFG_HIST','value')
    Trigger_hold_off.value=get_value(table.rows,'name', 'PCFG_TRG_HOLD','value')
    Trigger_output_width.value=get_value(table.rows,'name', 'PCFG_TRG_W','value')
    Gate_window.value =get_value(table.rows,'name', 'PCFG_GATE_W','value')
    polarity.value=(polarity.options[int(get_value(table.rows,'name','PCFG_POL','value'))])
    offset.value=get_value(table.rows,'name', 'PCFG_RAWOFS','value')
    # OFFSETS MENU TO BE MODIFIED SINCE OFFSETS SEEM TOP BE PER CHANNEL IN THIS FIRMWARE
    Probe_Selection.value=(Probe_Selection.options[int(get_value(table.rows,'name','PCFG_PRB_SEL','value'))])
    tau.value = (np.round((1E6*(2 * pi) / ((math.log((( int(get_value(table.rows,'name', 'PCFG_C11','value'),16) - 0.5 )/ 16384)))/(-2.71072)*ADC_SAMPLING_FREQ)),1))
    pz.value = np.round( 1E6* (32768 / (ADC_SAMPLING_FREQ*int(get_value(table.rows,'name', 'PCFG_CPZ','value'))  )) , 1)
    FLT_CFG_bits=bin(int(get_value(table.rows,'name', 'PCFG_FLT_CFG','value'), 16))[2:]
    Att1.value=int(str(FLT_CFG_bits[9:13]), 2)
    Att2.value=int(str(FLT_CFG_bits[5:9]), 2)
    BL_IN_Checkbox.value=bool(FLT_CFG_bits[4])
    PZ_Checkbox.value = bool(FLT_CFG_bits[3])
    Filter1_Checkbox.value= bool(FLT_CFG_bits[2])
    Filter2_Checkbox.value= bool(FLT_CFG_bits[1])
    BL_OUT_Checkbox.value= bool(FLT_CFG_bits[0])
    print('Parameter updated')
    ui.update
    return

def set_value(rows, key_search, value_search, key_to_modify, new_value):
    """
    Retourne la valeur associée à `key_return` dans la première ligne où
    `key_search` == `value_search`. Retourne None si aucune ligne ne correspond.
    """
    for row in rows:
        if row.get(key_search) == value_search:
            row[key_to_modify]= new_value
    return None

def registers_table_update():
    set_value(table.rows,'name', 'PCFG_THRS','value',Trigger_Thresh.value)
    set_value(table.rows,'name',  'PCFG_TRG_SOURCE','value',Trigger_Source.options.index(Trigger_Source.value))
    set_value(table.rows,'name',  'PCFG_TRG_MODE','value',Trigger_Mode.options.index(Trigger_Mode.value))
    set_value(table.rows,'name', 'PCFG_HIST','value',Trigger_hysteresis.value)
    set_value(table.rows,'name', 'PCFG_TRG_HOLD','value',Trigger_hold_off.value)
    set_value(table.rows,'name', 'PCFG_TRG_W','value',Trigger_output_width.value)
    set_value(table.rows,'name', 'PCFG_GATE_W','value',Gate_window.value)
    set_value(table.rows,'name', 'PCFG_POL','value',polarity.options.index(polarity.value))
    set_value(table.rows,'name', 'PCFG_RAWOFS','value',offset.value)
    # OFFSETS MENU TO BE MODIFIED SINCE OFFSETS SEEM TOP BE PER CHANNEL IN THIS FIRMWARE
    set_value(table.rows,'name', 'PCFG_PRB_SEL','value',Probe_Selection.options.index(Probe_Selection.value))
    
    TS = (2 * pi) / (tau.value*1E-6*ADC_SAMPLING_FREQ)
    pzcoeff2_d = (32768 / (ADC_SAMPLING_FREQ*pz.value*1E-6))
    coeff11_d = (math.exp(-2.71072*TS) * 16384 + 0.5)
    coeff12_d = (2 * math.exp(-1.35536*TS)*math.cos(0.327948*TS) * 16384 + 0.5)
    coeff21_d = (math.exp(-2.36216*TS) * 16384 + 0.5)
    coeff22_d = (2 * math.exp(-1.18108*TS)* math.cos(1.06037*TS) * 16384 + 0.5)

    pzcoeff2_h= hex(int(pzcoeff2_d)) 
    coeff11_h=hex(int(coeff11_d))
    coeff12_h=hex(int(coeff12_d))
    coeff21_h=hex(int(coeff21_d))
    coeff22_h=hex(int(coeff22_d))

    set_value(table.rows,'name', 'PCFG_CPZ','value',pzcoeff2_h)
    set_value(table.rows,'name', 'PCFG_C11','value',coeff11_h)
    set_value(table.rows,'name', 'PCFG_C12','value',coeff12_h)
    set_value(table.rows,'name', 'PCFG_C21','value',coeff21_h)
    set_value(table.rows,'name', 'PCFG_C22','value',coeff22_h)
    
    # FLT_CFG register value for the configuration of the filter stage
    Att1_bits=np.binary_repr(int(Att1.value), width=4)
    Att2_bits=np.binary_repr(int(Att2.value), width=4)
    BL_in_bit=np.binary_repr(BL_IN_Checkbox.value, width=1)
    PZ_bit=np.binary_repr(PZ_Checkbox.value, width=1)
    G1_bit=np.binary_repr(Filter1_Checkbox.value, width=1)
    G2_bit=np.binary_repr(Filter2_Checkbox.value, width=1)
    BL_out_bit=np.binary_repr(BL_OUT_Checkbox.value, width=1)

    FLT_CFG_bits='000'+BL_out_bit+G1_bit+G2_bit+PZ_bit+BL_in_bit+Att2_bits+Att1_bits
    print(FLT_CFG_bits)

    def bin_to_hex(binary_str):
        return hex(int(binary_str, 2))[2:] 

    set_value(table.rows,'name', 'PCFG_FLT_CFG','value',bin_to_hex(FLT_CFG_bits))

    print("update registers table")
    ui.update(table)
    ui.update()

def save_IP_config():
    print('Save IP config')


#####################################################################################
#  GUI window 
# ###################################################################################
# Tab title
if GUI_debug_mode:
    ui.page_title('QDIV-gui - Test Mode')
else:
    ui.page_title('QDIV-gui')
# GUI title
with html.section().style('font-size: 120%'):
    html.strong('QDIV-gui ') \
        .classes('cursor-pointer') \
        .tooltip('Version 2026-06-07')
        #.on('click', lambda: ui.notify('Version 2026-06-07'))
    html.hr()
    html.em('Graphical User Interface for position-sensitive neutron detectors read-out by the resistive-charge-division method with CAEN digitizers')
    #html.em('GUI version 2026-05-06 / R5560 Firmware version DPP-QDIV-XXXX-XX-X')   
# Detector type and read-out modes selection
with ui.row().classes('w-full no-wrap'):
    with ui.row().classes('w-full'):
        detType = ui.select(detTypeList,label='Detector type',value=detTypeInit,on_change=detTypeButton_change).classes('w-1/3')
        serial_number = ui.number(label='Serial number',value=1,on_change=serialNumberButton_change).classes('w-1/6')
        acqMode = ui.select(acqModeList,label='Acquisition mode',value=acqModeInit,on_change=acqModeButton_change).classes('w-1/3')
# GUI menus
    with ui.row().classes('justify-end'):
        with ui.tabs() as tabs:
            ui.tab('h', label='Acquisition', icon='image')
            ui.tab('f', label='Oscilloscope', icon='filter')
            #ui.tab('c', label='Connection', icon='lan')
            ui.tab('r', label='Digitiser', icon='settings')
            #ui.tab('v', label='Version', icon='help')

with ui.tab_panels(tabs, value='h').classes('w-full'):
    # Home menu : acquisition parameters and file saving options
    with ui.tab_panel('h'):
        with ui.row().classes('w-full no-wrap'):
            with ui.column().classes('w-1/8'):
                    startToggleButton=ToggleButton(text='Start').classes('w-full')
                    expT=ui.number(label='Acquisition time (s)', value=1.0, format='%.2f',)
                    expN=ui.number(label='Number of acquisitions', value=1, format='%d')
                    autosaveCheckbox = ui.checkbox('Autosave',value=True,on_change=autosave_click)
                    filenameInput=ui.input(label='Filename', value=filenameInit,
                    validation={'Input too long': lambda value: len(value) < 30})
                    subpathInput=ui.input(label='Subpath',value=subpathInit,
                    validation={'Input too long': lambda value: len(value) < 35})
                    pathInput=ui.input(label='Path',value=pathInit,
                    validation={'Input too long': lambda value: len(value) < 30})
            with ui.column().classes('w-full justify-center no-wrap'):
                FIGURE=ui.plotly(fig[0]).classes('w-full justify-center no-wrap')
                p=ui.pagination(1,nbOfFigsList[acqModeInit-1],direction_links=True,on_change=update_fig).classes('w-full justify-center no-wrap')
#               print(acqModeInit)
#                print(nbOfFigsList[acqModeInit-1])
                #ui.label().bind_text_from(p,'value',lambda v:f'Page{v}')
            #FIGURE=ui.plotly(fig).classes('w-150 h-150')
    # Filter menu 
    with ui.tab_panel('f'):
        with ui.row().classes('w-full no-wrap'):
            with ui.column().classes('w-1/8'):
                html.b('Trigger')
                Trigger_Thresh=ui.number(label='Threshold [0-65535]', value=0, format='%d').classes('w-full')
                Trigger_Source = ui.select(label='Source',options=["Filter output","Filter input"], value="Filter output").classes('w-full')
                Trigger_Mode = ui.select(label='Mode',options=["A+B","No internal trigger","A or B","A & B"], value="A+B").classes('w-full')
                Trigger_hysteresis = ui.number(label='Hysteresis [0-65535]', value=1000, format='%d').classes('w-full') 
                Trigger_hold_off = ui.number(label='Hold-off time (us)', value=1000, format='%d').classes('w-full')
                Trigger_output_width = ui.number(label='Trigger output width (us)', value=1000, format='%d').classes('w-full')
                Gate_window = ui.number(label='Gate window (us)', value=100, format='%d').classes('w-full')

                html.b('Input stage')
                polarity = ui.select(label='Polarity',options=["Positive","Negative"], value="Positive").classes('w-full')
                offset=ui.number(label='Offset [0-65535]', value=20000, format='%d').classes('w-full')
            with ui.column().classes('w-1/8'):
                html.b('Digital filter')
                tau=ui.number(label='Shaping time (us)', value=1.0, format='%.1f').classes('w-full')
                pz=ui.number(label='Pole Zero (us)', value=1.0, format='%.1f').classes('w-full')
                Att1=ui.number(label='Filter 1 att. [0-7]', value=1, format='%d').classes('w-full')
                Att2=ui.number(label='Filter 2 att. [0-7]', value=1, format='%d').classes('w-full')
                BL_IN_Checkbox = ui.checkbox('BL IN',value=True,on_change=autosave_click).classes('w-full')
                PZ_Checkbox = ui.checkbox('PZ',value=True,on_change=autosave_click).classes('w-full')
                Filter1_Checkbox = ui.checkbox('Filter 1',value=True,on_change=autosave_click).classes('w-full')
                Filter2_Checkbox = ui.checkbox('Filter 2',value=True,on_change=autosave_click).classes('w-full')
                BL_OUT_Checkbox = ui.checkbox('BL OUT',value=True,on_change=autosave_click).classes('w-full')
            with ui.column().classes('w-1/8'):
                registers_table_update_button=ui.button(text='Apply settings',color='green',on_click=lambda:(registers_table_update(),setADCsettings())).classes('w-full')
                line_updates = ui.timer(0.1, update_all, active=False)
                scope_switch = ui.switch('Run / Stop').bind_value_to(line_updates,'active')
                scope_trigger_mode=ui.select(label='Scope trigger mode',options=["disabled", "self", "analog", "ext", "digital" ], value="self").classes('w-full')
                scope_threshold_slider = ui.slider(min=0, max=2**16, value=10000)
                scope_trig_ch_button =  ui.select(label='Scope trigger channel',options=["Channel A","Channel B"], value="Channel A").classes('w-full')
                ui.label().bind_text_from(scope_threshold_slider, 'value')
                tube_number=ui.number(label='Tube number', value=0, format='%d').classes('w-full')
                an_mon_sel_options=["signal with corrected offset and polarity",
                "signal with corrected offset only",
                "main filter output",
                "sum of both side main filter output",
                "peak detector output",
                "peak detector output on sum signal",
                "input baseline correction algorithm output",
                "pz algorithm output",
                "first filter algorithm output (divided by 2)",
                "second filter algorithm output (divided by 2)",
                "output baseline algorithm output (divided by 2)"]
                Probe_Selection = ui.select(label='Probe selection',options=an_mon_sel_options, value=an_mon_sel_options[2]).classes('w-full')
                
                traces_autosaveCheckbox = ui.checkbox('Save traces',value=False,on_change=traces_autosave_click)
                number_of_traces_input = ui.number(label='Number of traces', value=10, format='%d').classes('w-full')
                traces_filenameInput=ui.input(label='Filename', value=traces_filenameInit,
                validation={'Input too long': lambda value: len(value) < 30})
                traces_subpathInput=ui.input(label='Traces_Subpath',value=traces_subpathInit,
                validation={'Input too long': lambda value: len(value) < 35})
                traces_pathInput=ui.input(label='Path',value=pathInit,
                validation={'Input too long': lambda value: len(value) < 30})
                number_of_traces_input.visible=False
                traces_pathInput.visible=False
                traces_subpathInput.visible=False
                traces_filenameInput.visible=False


            with ui.column().classes('w-3/8 justify-center no-wrap'):  
                analog_line_plot = ui.line_plot(n=4, limit=1024,update_every=1)\
                    .with_legend(['Channel A input', 'Channel B input','Channel A output','Channel B output'], loc='upper right', ncol=1)
                
                digital_line_plot = ui.line_plot(n=4, limit=1024, update_every=1) \
                    .with_legend(['Trigger', 'Over thresh.','Gate','Energy ready'], loc='upper right', ncol=1)
            
            with ui.column().classes('w-1/8'):
                html.b('Noise [ADUs rms]')
                rms_val_ch1=ui.number(label='Channel A input :', value=0.0, format='%.2f').classes('w-full')
                rms_val_ch2=ui.number(label='Channel B input :', value=0.0, format='%.2f').classes('w-full')
                rms_val_ch3=ui.number(label='Channel A output :', value=0.0, format='%.2f').classes('w-full')
                rms_val_ch4=ui.number(label='Channel B output :', value=0.0, format='%.2f').classes('w-full')
            with ui.column().classes('w-1/8'):
                html.b('Offset [ADUs]')
                mean_val_ch1=ui.number(label='Channel A input :', value=0.0, format='%.2f').classes('w-full')
                mean_val_ch2=ui.number(label='Channel B input :', value=0.0, format='%.2f').classes('w-full')
                mean_val_ch3=ui.number(label='Channel A output :', value=0.0, format='%.2f').classes('w-full')
                mean_val_ch4=ui.number(label='Channel B ouput :', value=0.0, format='%.2f').classes('w-full')


    with ui.tab_panel('r'):
        with ui.row().classes('w-full'):
            with ui.column().classes('w-1/4'):
                print(det_list['CSPEC']['nbOfTubes'])
                print(detTypeList[detType.value])
                print(round(int(det_list['CSPEC']['nbOfTubes'])/16))
                html.b('R5560 Firmware')
                firmware_button=ui.input(label='Version', value='QDIV_CSPEC_CT2_April_2026').classes('w-full')
                html.b('R5560 IP addresses')
                RJ45_port_IP=[]
                for RJ45_port_number in range(round(int(det_list[detTypeList[detType.value]]['nbOfTubes'])/16)):
                    RJ45_port_IP.append(ui.input(label='RJ45 port ' + str(RJ45_port_number), value=IP[RJ45_port_number]).classes('w-1/3'))
                save_IP_button=ui.button(text='Save config',color='red',on_click=lambda:(save_IP_config(),ui.notify('IP configuration saved !'))).classes('w-full')
                

            with ui.column().classes('w-1/2'):
                html.b('R5560 Registers')
                # Function to refresh the table after edits
                def refresh_table(reg_rows):
                    table.rows = reg_rows

                # Function to handle inline edits
                def update_cell(row_id, field, value):
                    for r in reg_rows:
                        if r['id'] == row_id:
                            r[field] = value
                            break
                    ui.notify(f"Updated row {row_id}: {field} = {value}")

                # Create the table
                (reg_rows,reg_columns)=openRegisterFile(register_filename_default)
                table = ui.table(columns=reg_columns, rows=reg_rows, row_key='id', pagination=6).classes('w-full')
                

                # Editable Name column
                table.add_slot('body-cell-name', r'''
                <q-td :props="props">
                    <q-input dense v-model="props.row.name" @update:model-value="val => $parent.$emit('cell-edit', {id: props.row.id, field: 'name', value: val})" />
                </q-td>
                ''')

                # Editable Age column
                table.add_slot('body-cell-age', r'''
                <q-td :props="props">
                    <q-input type="number" dense v-model.number="props.row.age" @update:model-value="val => $parent.$emit('cell-edit', {id: props.row.id, field: 'age', value: val})" />
                </q-td>
                ''')

                # Event listeners for edits and deletes
                table.on('cell-edit', lambda e: update_cell(e.args['id'], e.args['field'], e.args['value']))
            
            with ui.column().classes('w-1/5'):
                # #ui.button('Choose Files', on_click=choose_files)
                # register_filename=ui.input(label='Register filename', value=register_filename_default,
                # validation={'Input too long': lambda value: len(value) < 50}).classes('w-full')
                # open_regs_file_button=ui.button(text='open register file',on_click=lambda:(openRegisterFile(register_filename.value),ui.notify('Register file opened !'))).classes('w-full')
                # save_regs_file_button=ui.button(text='save register file',color='red',on_click=lambda:(ui.table.update(),saveRegisterFile(register_filename.value,reg_rows),ui.notify('Register file saved !'))).classes('w-full')
                # set_regs_button=ui.button(text='Set registers',color='green',on_click=lambda:(setADCsettings(),ui.notify('Registers updated !'))).classes('w-full')
                # get_regs_button=ui.button(text='Get registers',color='green',on_click=lambda:(getADCsettings(),ui.notify('Table updated !'))).classes('w-full')

                register_filename=ui.input(label='Register filename', value=register_filename_default,
                validation={'Input too long': lambda value: len(value) < 50}).classes('w-full')
                open_regs_file_button=ui.button(text='open register file',on_click=lambda:(openRegisterFile(register_filename.value),ui.notify('Register file opened !'))).classes('w-full')
                save_regs_file_button=ui.button(text='save register file',color='red',on_click=lambda:(ui.table.update(),saveRegisterFile(register_filename.value,reg_rows),ui.notify('Register file saved !'))).classes('w-full')
                set_regs_button=ui.button(text='Set registers',color='green',on_click=lambda:(setADCsettings(),ui.notify('Registers updated !'))).classes('w-full')
                get_regs_button=ui.button(text='Get registers',color='green',on_click=lambda:(getADCsettings(),ui.notify('Table updated !'))).classes('w-full')



#sdk=connect()
sdk=connect()
setADCsettings()
scope_parameters_update()

buf_osc=apply_scope_settings()

ui.run()



